name: Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
env:
  ## Sets environment variable
  IS_LOCAL: false
  PUSH_EVENT: ${{ github.event_name == 'push'}}

permissions:
  id-token: write
  contents: write
  
jobs:
 Platform-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
