name: Platform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
env:
  ## Sets environment variable
  IS_LOCAL: false
  PUSH_EVENT: ${{ github.event_name == 'push'}}
  ubl: "ubuntu-latest

permissions:
  id-token: write
  contents: write
  
jobs:
 Platform-Build:
   runs-on: ${ubl}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      -  name: Cache node modules
         id: cache-nodemodules
         uses: actions/cache@v2
         env:
            cache-name: cache-node-modules
         with:
            # caching node_modules
            path: node_modules
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-build-${{ env.cache-name }}-
              ${{ runner.os }}-build-
              ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name:  Build
        run : npm run build -- --stage dev

      - name: Upload a Build Artifact ${ebl}
        if: ${{ env.PUSH_EVENT }}
        uses: actions/upload-artifact@v2
        with:
            name: build
            # do we need to specify any custom path ${ebl}
            path: .build/build.out                      

      - name : Test
        run: npm run test
        continue-on-error: false


